# Generated by Django 5.0.6 on 2024-08-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sineverseApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usedetails',
            old_name='telegramID',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='usedetails',
            name='user',
        ),
        migrations.AddField(
            model_name='usedetails',
            name='tgID',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usedetails',
            name='tgUsername',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
