# Generated by Django 5.0.6 on 2024-08-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sineverseApp', '0003_rename_usedetails_userdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='goldPoint',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='level',
            field=models.CharField(blank=True, choices=[('Level 1', 'Level 1'), ('Level 2', 'Level 2'), ('Level 3', 'Level 3')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='miningPoint',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
