# Generated by Django 5.0.6 on 2024-08-13 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sineverseApp', '0004_userdetails_goldpoint_userdetails_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MineBoost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superDescription', models.CharField(blank=True, max_length=255, null=True)),
                ('silverDescription', models.CharField(blank=True, max_length=255, null=True)),
                ('goldDescription', models.CharField(blank=True, max_length=255, null=True)),
                ('mineBoostLevel', models.CharField(blank=True, choices=[('Super Mine', 'Super Mine'), ('Silver Mine', 'Silver Mine'), ('Gold Mine', 'Gold Mine')], max_length=255, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sineverseApp.userdetails')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseMine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amountToPurchased', models.FloatField(blank=True, null=True)),
                ('mineBoost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sineverseApp.mineboost')),
            ],
        ),
    ]
