# Generated by Django 5.0.6 on 2024-08-13 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sineverseApp', '0005_mineboost_purchasemine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mineboost',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mine_boost', to='sineverseApp.userdetails'),
        ),
        migrations.CreateModel(
            name='DailyReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amountGained', models.IntegerField(blank=True, default=1000, null=True)),
                ('trackEachDayCount', models.IntegerField(blank=True, default=0, null=True)),
                ('last_claimed', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_reward', to='sineverseApp.userdetails')),
            ],
        ),
    ]
