# Generated by Django 5.0.6 on 2024-08-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sineverseApp', '0006_alter_mineboost_user_dailyreward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreward',
            name='amountGained',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
