# Generated by Django 5.0.6 on 2024-08-15 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sineverseApp', '0009_dailyreward_tid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyreward',
            old_name='tID',
            new_name='tgID',
        ),
    ]
