# Generated by Django 5.0.6 on 2024-08-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sineverseApp', '0010_rename_tid_dailyreward_tgid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreward',
            name='amountGained',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
