# Generated by Django 5.0.6 on 2024-08-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sineverseApp', '0011_alter_dailyreward_amountgained'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreward',
            name='oldAmount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
