# Generated by Django 5.0.6 on 2024-08-15 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sineverseApp', '0013_walletaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletaddress',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_address', to='sineverseApp.userdetails'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ListInvites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inviteCode', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='sineverseApp.userdetails')),
            ],
        ),
    ]
