# Generated by Django 5.0.6 on 2024-08-15 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sineverseApp', '0015_remove_userdetails_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ListInvites',
            new_name='ListOfInvites',
        ),
        migrations.AlterField(
            model_name='dailyreward',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reward', to='sineverseApp.userdetails'),
        ),
    ]
