# Generated by Django 5.0.6 on 2024-08-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sineverseApp', '0016_rename_listinvites_listofinvites_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='avatar',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
