# Generated by Django 5.0.6 on 2024-08-19 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sineverseApp', '0018_remove_purchasemine_mineboost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreward',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_reward', to='sineverseApp.userdetails'),
        ),
        migrations.AlterField(
            model_name='listofinvites',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='sineverseApp.userdetails'),
        ),
        migrations.AlterField(
            model_name='walletaddress',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_address', to='sineverseApp.userdetails'),
        ),
    ]
