# Generated by Django 5.0.6 on 2024-08-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sineverseApp', '0019_alter_dailyreward_user_alter_listofinvites_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='maxEnergyLevel',
            field=models.IntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
