# Generated by Django 5.0.6 on 2024-08-20 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sineverseApp', '0022_alter_dailyreward_last_claimed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldcoin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gold_coin', to='sineverseApp.userdetails'),
        ),
    ]
