# Generated by Django 5.0.6 on 2024-08-20 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sineverseApp', '0024_alter_goldcoin_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldcoin',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gold_coin', to='sineverseApp.userdetails'),
        ),
    ]
