# Generated by Django 5.0.6 on 2024-08-20 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sineverseApp', '0026_alter_dailyreward_user_alter_silvercoin_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listofinvites',
            name='inviteCode',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='earned_energy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='referral_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='sineverseApp.userdetails'),
        ),
    ]
