# Generated by Django 5.0.6 on 2024-08-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sineverseApp', '0027_remove_listofinvites_invitecode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='reward_earned',
            field=models.IntegerField(default=0),
        ),
    ]
