# Generated by Django 5.0.6 on 2024-08-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sineverseApp', '0028_userdetails_reward_earned'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='last_claimed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
