# Generated by Django 5.0.6 on 2024-08-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sineverseApp', '0029_userdetails_last_claimed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='last_claimed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
