# Generated by Django 5.0.6 on 2024-08-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sineverseApp', '0031_userdetails_social_task_earned_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='social_task_earned',
            new_name='telegram_channel_earned',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='telegram_group_earned',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='x_earned',
            field=models.IntegerField(default=0),
        ),
    ]
