# Generated by Django 5.0.6 on 2024-08-23 18:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sineverseApp', '0032_rename_social_task_earned_userdetails_telegram_channel_earned_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRewardHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amountGained', models.IntegerField(default=0)),
                ('date_claimed', models.DateField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_history', to='sineverseApp.userdetails')),
            ],
        ),
    ]
