# Generated by Django 5.0.6 on 2024-08-23 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sineverseApp', '0033_dailyrewardhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyRewardHistory',
        ),
    ]
